import { useEffect, useRef, useState } from "react";
import { fetchAnalystStatus, postAnalystAsk, fetchStrategyRaces } from "../api/client";
import { useSeason } from "../context/SeasonContext";

/* Phase 5 — AI Race Analyst: conversational Q&A grounded in RaceDelta's own telemetry tools */

const select = "bg-[#0f172a] border border-gray-700 rounded-lg p-2 text-white text-sm";

function Sources({ tools }) {
  const [open, setOpen] = useState(false);
  if (!tools?.length) return null;
  return (
    <div className="mt-2 text-xs">
      <button onClick={() => setOpen(!open)} className="text-gray-400 hover:text-gray-200">
        {open ? "▾" : "▸"} Sources · {tools.length} tool call{tools.length > 1 ? "s" : ""} ({tools.map((t) => t.name).join(", ")})
      </button>
      {open && (
        <ul className="mt-2 space-y-2 border-l border-gray-700 pl-3">
          {tools.map((t, i) => (
            <li key={i}>
              <div className={`font-mono ${t.error ? "text-red-400" : "text-gray-300"}`}>{t.name}({Object.entries(t.input || {}).map(([k, v]) => `${k}=${JSON.stringify(v)}`).join(", ")})</div>
              <div className="text-gray-400">{t.summary}</div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

export default function RaceAnalyst() {
  const { seasonOptions, displaySeason } = useSeason();
  const [season, setSeason] = useState(displaySeason || new Date().getFullYear());
  const [races, setRaces] = useState([]);
  const [round, setRound] = useState("");
  const [status, setStatus] = useState(null);
  const [messages, setMessages] = useState([]);   // {role, content, tools_used?, mode?}
  const [input, setInput] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const bottom = useRef(null);

  useEffect(() => { fetchAnalystStatus().then(setStatus).catch(() => setStatus(null)); }, []);
  useEffect(() => { if (displaySeason) setSeason(displaySeason); }, [displaySeason]);
  useEffect(() => {
    setRaces([]); setRound("");
    fetchStrategyRaces(season).then((r) => { setRaces(r.races); setRound(r.races[0]?.round ?? ""); }).catch((e) => setError(e.message));
  }, [season]);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, busy]);

  async function send(text) {
    const question = (text ?? input).trim();
    if (!question || busy) return;
    setInput(""); setError("");
    const history = messages.map((m) => ({ role: m.role, content: m.content }));
    setMessages((m) => [...m, { role: "user", content: question }]);
    setBusy(true);
    try {
      const res = await postAnalystAsk({ question, season, round: round ? Number(round) : undefined, history });
      setMessages((m) => [...m, { role: "assistant", content: res.answer, tools_used: res.tools_used, mode: res.mode, model: res.model }]);
    } catch (e) {
      setError(e.message);
    } finally { setBusy(false); }
  }

  const race = races.find((r) => String(r.round) === String(round));
  const live = status?.mode === "claude";

  return (
    <div className="max-w-5xl mx-auto px-6 py-8 space-y-6 text-white">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold">AI Race Analyst</h1>
          <p className="text-gray-400 text-sm mt-1">Ask about a race. Every answer is built only from RaceDelta's telemetry, feature store, Strategy Lab and driver intelligence.</p>
        </div>
        <div className="flex gap-2 flex-wrap items-center">
          <span className={`text-xs px-2 py-1 rounded-full border ${live ? "border-green-500/40 text-green-400" : "border-amber-500/40 text-amber-400"}`}
                title={live ? "Answers generated by Claude with tool calling" : "No ANTHROPIC_API_KEY set: rule-based intent detection over the same tools"}>
            {live ? `Claude · ${status.model}` : "Offline intent mode"}
          </span>
          <select className={select} value={season} onChange={(e) => setSeason(Number(e.target.value))}>
            {seasonOptions.length ? seasonOptions.map((o) => <option key={o.value} value={o.value}>{o.label}</option>) : <option value={season}>{season}</option>}
          </select>
          <select className={select} value={round} onChange={(e) => setRound(e.target.value)}>
            <option value="">Season-wide</option>
            {races.map((r) => <option key={r.round} value={r.round}>R{r.round} · {r.event}{r.ingested === false ? " (loads on first question)" : ""}</option>)}
          </select>
        </div>
      </div>

      {error && <div className="bg-red-500/10 border border-red-500/30 p-4 rounded-lg text-red-400">{error}</div>}

      <div className="bg-[#0b1220] rounded-xl p-4 shadow-lg min-h-[420px] max-h-[60vh] overflow-y-auto space-y-4">
        {messages.length === 0 && (
          <div className="text-gray-400 text-sm space-y-3">
            <p>{race ? `Context: ${race.event} (${season} R${race.round}, ${race.total_laps} laps).` : "Pick a race for race-specific questions, or ask season-wide questions like driver ratings."} Try:</p>
            <div className="flex flex-wrap gap-2">
              {(status?.suggested_questions || []).map((q) => (
                <button key={q} onClick={() => send(q)} className="text-xs border border-gray-700 hover:border-red-500 rounded-full px-3 py-1 text-gray-200">{q}</button>
              ))}
            </div>
          </div>
        )}
        {messages.map((m, i) => (
          <div key={i} className={`flex ${m.role === "user" ? "justify-end" : "justify-start"}`}>
            <div className={`max-w-[85%] rounded-xl px-4 py-3 text-sm whitespace-pre-wrap ${m.role === "user" ? "bg-[#ff1801] text-white" : "bg-[#0f172a] border border-gray-700"}`}>
              {m.content}
              {m.role === "assistant" && <Sources tools={m.tools_used} />}
              {m.role === "assistant" && m.mode === "offline" && <div className="mt-1 text-[10px] uppercase tracking-wide text-amber-400/80">offline intent mode</div>}
            </div>
          </div>
        ))}
        {busy && <div className="text-gray-400 text-sm animate-pulse">Analysing telemetry…</div>}
        <div ref={bottom} />
      </div>

      <form onSubmit={(e) => { e.preventDefault(); send(); }} className="flex gap-2">
        <input value={input} onChange={(e) => setInput(e.target.value)} placeholder={race ? `Ask about ${race.event}…` : "Ask a question…"}
               className="flex-1 bg-[#0f172a] border border-gray-700 rounded-lg p-3 text-white text-sm" />
        <button type="submit" disabled={busy || !input.trim()} className="bg-[#ff1801] hover:bg-red-600 disabled:opacity-50 text-white font-semibold px-5 rounded-lg">Ask</button>
        {messages.length > 0 && <button type="button" onClick={() => setMessages([])} className="text-gray-400 hover:text-white text-sm px-2">Clear</button>}
      </form>
    </div>
  );
}
