import { useEffect, useRef, useState } from "react";
import { fetchAnalystStatus, postAnalystAsk, fetchStrategyRaces } from "../api/client";
import { useSeason } from "../context/SeasonContext";
import PageHeader from "../components/PageHeader";

/* Phase 5 — AI Race Analyst: conversational Q&A grounded in RaceDelta's own telemetry tools. Purple = AI output. */

function Sources({ tools }) {
  const [open, setOpen] = useState(false);
  if (!tools?.length) return null;
  return (
    <div className="mt-3 text-sm">
      <button type="button" onClick={() => setOpen(!open)} className="eyebrow eyebrow-ai hover:text-white">
        {open ? "▾" : "▸"} Sources · {tools.length} tool call{tools.length > 1 ? "s" : ""}
      </button>
      {open && (
        <ul className="mt-2 space-y-2 border-l-2 border-sector/50 pl-3">
          {tools.map((t, i) => (
            <li key={i}>
              <div className={`font-mono text-[0.85rem] ${t.error ? "text-f1" : "text-white"}`}>
                {t.name}({Object.entries(t.input || {}).map(([k, v]) => `${k}=${JSON.stringify(v)}`).join(", ")})
              </div>
              <div className="text-muted">{t.summary}</div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

export default function RaceAnalyst() {
  const { seasonOptions, displaySeason } = useSeason();
  const [season, setSeason] = useState(displaySeason || new Date().getFullYear());
  const [races, setRaces] = useState([]);
  const [round, setRound] = useState("");
  const [status, setStatus] = useState(null);
  const [messages, setMessages] = useState([]);   // {role, content, tools_used?, mode?}
  const [input, setInput] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const bottom = useRef(null);

  useEffect(() => { fetchAnalystStatus().then(setStatus).catch(() => setStatus(null)); }, []);
  useEffect(() => { if (displaySeason) setSeason(displaySeason); }, [displaySeason]);
  useEffect(() => {
    setRaces([]); setRound("");
    fetchStrategyRaces(season).then((r) => { setRaces(r.races); setRound(r.races[0]?.round ?? ""); }).catch((e) => setError(e.message));
  }, [season]);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: "smooth", block: "nearest" }); }, [messages, busy]);

  async function send(text) {
    const question = (text ?? input).trim();
    if (!question || busy) return;
    setInput(""); setError("");
    const history = messages.map((m) => ({ role: m.role, content: m.content }));
    setMessages((m) => [...m, { role: "user", content: question }]);
    setBusy(true);
    try {
      const res = await postAnalystAsk({ question, season, round: round ? Number(round) : undefined, history });
      setMessages((m) => [...m, { role: "assistant", content: res.answer, tools_used: res.tools_used, mode: res.mode, model: res.model }]);
    } catch (e) {
      setError(e.message);
    } finally { setBusy(false); }
  }

  const race = races.find((r) => String(r.round) === String(round));
  const live = status?.mode === "claude" || status?.mode === "nvidia";

  return (
    <div className="py-6 space-y-6 max-w-5xl mx-auto">
      <PageHeader
        kicker="AI Race Analyst"
        title="Race Analyst"
        season={season}
        subtitle="Ask about a race in plain language. Every answer is built only from RaceDelta's telemetry, feature store, Strategy Lab and driver intelligence, and shows its sources."
        actions={
          <div className="page-actions">
            <span className={`chip ${live ? "chip-live" : "chip-warn"}`} data-tour="analyst-mode"
                  title={live ? `Answers generated by ${status.model} with tool calling` : "No model API key set: rule-based intent detection over the same tools"}>
              {live ? status.model : "Offline intent mode"}
            </span>
            <select className="select-broadcast" value={season} onChange={(e) => setSeason(Number(e.target.value))} aria-label="Season">
              {seasonOptions.length ? seasonOptions.map((o) => <option key={o.value} value={o.value}>{o.label}</option>) : <option value={season}>{season}</option>}
            </select>
            <select className="select-broadcast" value={round} onChange={(e) => setRound(e.target.value)} aria-label="Race" data-tour="analyst-race">
              <option value="">Season-wide</option>
              {races.map((r) => <option key={r.round} value={r.round}>R{r.round} · {r.event}{r.ingested === false ? " (loads on first question)" : ""}</option>)}
            </select>
          </div>
        }
      />

      {error && <div className="panel panel-plain border-f1/40 p-4 text-f1">{error}</div>}

      <section className="panel panel-ai">
        <div className="panel-body min-h-[440px] max-h-[62vh] overflow-y-auto space-y-4">
          {messages.length === 0 && (
            <div className="space-y-4" data-tour="analyst-suggest">
              <p className="text-muted">
                {race ? `Context: ${race.event} (${season} R${race.round}, ${race.total_laps} laps).` : "Pick a race for race-specific questions, or ask season-wide questions like driver ratings."} Try one of these:
              </p>
              <div className="flex flex-wrap gap-2">
                {(status?.suggested_questions || []).map((q) => (
                  <button key={q} type="button" onClick={() => send(q)} className="chip chip-button normal-case tracking-normal font-body font-semibold text-[0.95rem] text-white">{q}</button>
                ))}
              </div>
            </div>
          )}
          {messages.map((m, i) => (
            <div key={i} className={`flex ${m.role === "user" ? "justify-end" : "justify-start"}`}>
              <div className={`max-w-[85%] px-4 py-3 text-[1rem] leading-relaxed whitespace-pre-wrap ${
                m.role === "user" ? "bg-f1 text-white" : "bg-raised border border-line border-l-2 border-l-sector"}`}>
                {m.role === "assistant" && <div className="eyebrow eyebrow-ai mb-1">RaceDelta analyst{m.mode === "offline" ? " · offline intent mode" : ""}</div>}
                {m.content}
                {m.role === "assistant" && <Sources tools={m.tools_used} />}
              </div>
            </div>
          ))}
          {busy && <div className="text-muted animate-pulse">Analysing telemetry…</div>}
          <div ref={bottom} />
        </div>
      </section>

      <form onSubmit={(e) => { e.preventDefault(); send(); }} className="flex gap-2" data-tour="analyst-input">
        <input value={input} onChange={(e) => setInput(e.target.value)} placeholder={race ? `Ask about ${race.event}…` : "Ask a question…"}
               className="input-broadcast flex-1" aria-label="Your question" />
        <button type="submit" disabled={busy || !input.trim()} className="btn-primary">Ask</button>
        {messages.length > 0 && <button type="button" onClick={() => setMessages([])} className="btn-ghost">Clear</button>}
      </form>
    </div>
  );
}
